debreach.lo: /home/brandon/blib-better/debreach_module/debreach.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/brandon/blib-better/debreach_module $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/brandon/blib-better/debreach_module/debreach.c -o debreach.lo 
$(phplibdir)/debreach.la: ./debreach.la
	$(LIBTOOL) --mode=install cp ./debreach.la $(phplibdir)

./debreach.la: $(shared_objects_debreach) $(DEBREACH_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_debreach) $(DEBREACH_SHARED_LIBADD)

